cook_ebook/urls.py
""" Django's urls.py for specifying the url paths for each of
my class based views in views.py """
from django.urls import path
from . import views

urlpatterns = [
    path('', views.TagList.as_view(), name='home'),
    path(
        'search-recipes/',
        views.RecipeSearchView.as_view(),
        name='search_recipes'
        ),
    path(
        'search-tags/<str:tag>',
        views.RecipeByTagView.as_view(),
        name='search_tags'
        ),
    path(
        'recipe-details/<slug:slug>',
        views.RecipeDetailsView.as_view(),
        name='recipe_details'
        ),
    path(
        'recipe-chefs-kiss/<slug:slug>',
        views.RecipeChefsKissView.as_view(),
        name='recipe_chefs_kiss'
        ),
    path(
        'my-ebook/<str:username>',
        views.UsereBookView.as_view(),
        name='my_ebook'
        ),
    path(
        'my-ebook-search-recipes/',
        views.MyeBookRecipeSearchView.as_view(),
        name='my_ebook_search_recipes'
        ),
    path(
        'my-ebook-tags-search/<str:tag>',
        views.MyeBookTagSearchView.as_view(),
        name='ebook_search_tags'
        ),
    path(
        'create-recipe/',
        views.CreateRecipeView.as_view(),
        name='create_recipe'
        ),
    path(
        'edit-recipe/<slug:slug>',
        views.EditRecipeView.as_view(),
        name='edit_recipe'
        ),
    path(
        'delete-recipe/<slug:slug>',
        views.DeleteRecipeView.as_view(),
        name='delete_recipe'
        ),
    path(
        'about/',
        views.AboutPageView.as_view(),
        name='about'
        ),
]

project_four/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cook_ebook.urls')),
    path('accounts/', include('allauth.urls')),
]

cook_ebook/models.py
"""
Django's models.py where I have created the classes
for each of my database tables
"""

import random
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from colorfield.fields import ColorField


# tuple for storing the possible values for a recipe's public_status
PUBLIC_STATUS = ((0, 'Private'), (1, 'Public'), (2, 'Awaits'))


class Tag(models.Model):
    """
    Class for Tag table in the database
    Contains:
    -tag field (label for each tag)
    -color field (unique color for each tag)
    """
    tag = models.CharField(max_length=100)
    color = ColorField(unique=True)

    def __str__(self):
        return str(self.tag)


def random_slug():
    """
    Method for generating a random string of digits.
    Used by the slugField default in the Recipe class.
    This method:
    -generates a list of 20 random integers in the range 0 to 100
    -turns the integer list into a string list
    -joins all the string list items into one string
    -returns the string
    """
    random_numbers_list = [random.randint(0, 100) for i in range(20)]
    random_str_list = [str(i) for i in random_numbers_list]
    random_str = str("".join(random_str_list))

    return random_str


class Recipe(models.Model):
    """
    Creating the Recipe class which inherits Django's models.Model and
    represents the Recipe table in the database
    Contains the fields:
    -title
    -summary
    -cover_image
    -tags (many-to-many relationship)
    -public_status
    -created_date
    -chef (foreign-key relationship)
    -slug
    -chefs_kisses (many-to-many relationship)
    """
    title = models.CharField(max_length=80)
    summary = models.TextField(max_length=200, blank=True)
    cover_image = CloudinaryField('image', default='placeholder')
    tags = models.ManyToManyField(Tag, blank=True, related_name='recipe_tag')
    public_status = models.IntegerField(choices=PUBLIC_STATUS, default=0)
    created_date = models.DateTimeField(auto_now_add=True)
    chef = models.ForeignKey(
        User, on_delete=models.CASCADE,
        related_name='recipe_creator'
    )
    slug = models.SlugField(max_length=200, unique=True, default=random_slug)
    chefs_kisses = models.ManyToManyField(
        User,
        blank=True,
        related_name='recipe_chefs_kiss'
    )

    class Meta:
        """ meta data for how to order recipes """
        ordering = ['-created_date']

    def __str__(self):
        """ method to return the title as a string for each recipe """
        return str(self.title)

    def number_of_chefs_kisses(self):
        """ method for counting the number of chefs_kisses for a recipe """
        return self.chefs_kisses.count()


class Ingredient(models.Model):
    """
    Class for Ingredient table in the database
    Contains:
    -item field (label for each item)
    -recipe (foreign-key relationship)
    """
    item = models.CharField(max_length=200)
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE,
        related_name="items",
        null=True
    )

    def __str__(self):
        """ method to return the item as a string for each ingredient """
        return str(self.item)


class Method(models.Model):
    """
    Class for Method table in the database
    Contains:
    -step field (label for each step)
    -recipe (foreign-key relationship)
    """
    step = models.CharField(max_length=400)
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name="steps",
        null=True
    )

    def __str__(self):
        """ method to return the step as a string for each method step """
        return str(self.step)

templates/about.html
{% extends "base.html" %}
{% load static %}

<!-- additional content for title element -->
{% block head_title_extra %} About {% endblock %}

{% block content %}
<!-- container for all the content to be used with base.html main section -->
<div class="container align-self-center">

    <!-- about page heading -->
    <div class="row site-intro-container">
        <div class="col-12 text-center p-2">
            <h1 id="about-header">
                About <br>
                Cook eBook
            </h1>
        </div>
    </div>

    <!-- site creator section -->
    <div class="row">
        <div class="col-12 text-center my-4">
            <h3 class="fw-bold">Site Creator:</h3>
            <p>
                mountaincharlie <br>
                Student Web Developer <br>
                Find me on
                <!-- link to mountaincharlie GitHub profile -->
                <a class="fw-bold text-muted text-decoration-none" href="https://github.com/mountaincharlie" target = "_blank" rel = "noopener noreffer" aria-label="Link to mountaincharlie's GitHub profile">GitHub</a>
            </p>
        </div>
    </div>

    <!-- site purpose section -->
    <div class="row">
        <div class="col-12 text-center my-4">
            <h3 class="fw-bold">Site Purpose:</h3>
            <p class="px-4">
                Cook eBook is a place where user's can view recipes created by others, as well as create and edit their own.<br>
                Built with mobile-first design in mind, Cook eBook is convenient and easy to take with you and use wherever you go. <br>
                Check out the 
                <!-- link to Cook eBook GitHub repo -->
                <a class="fw-bold text-muted text-decoration-none" href="https://github.com/mountaincharlie/project-four-cook-ebook" target = "_blank" rel = "noopener noreffer" aria-label="Link to mountaincharlie's GitHub repo for Cook eBook">Cook eBook Repo</a>
            </p>
        </div>
    </div>

    <!-- give feedback section - only displayed if the user is logged in -->
    {% if user.is_authenticated %}
    <div class="row">
        <div class="col-12 text-center my-4">
            <h3 class="fw-bold">Give Feedback:</h3>
            <p>
                I'd love to hear what you think of Cook eBook <br>
                Find me on
                <!-- link to code_by_charlie Instagram page -->
                <a class="fw-bold text-muted text-decoration-none" href="https://www.instagram.com/code_by_charlie97/" target = "_blank" rel = "noopener noreffer" aria-label="Link to code_by_charlie97's Instagram account">
                    <i class="fa-brands fa-instagram"></i>
                    Instagram
                </a>
            </p>
        </div>
    </div>
    {% endif %}

</div>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Cook eBook is a recipe making community, where users can view public recipes made by others and create, organise and edit their own in their personal eBook."> 
        <meta name="keywords" content="recipe, cook, cooking, cookbook, food, create, edit, chef, mobile, tags, eat"> 
        <meta name="author" content="Charlie Harland">

        <!-- google font api link -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato|Raleway">

        <!-- font awesome cdn -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">

        <!-- bootstrap cdn -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

        <!-- favicon link -->
        <link href = "{% static 'images/cookie-favicon.png' %}" rel = "shortcut icon" type = "image/x-icon">

        <!-- linked css file -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

        <!-- custom title which can be added to in the templates which extend base.html -->
        <title>Cook eBook {% block head_title_extra %}{% endblock %}</title>
    </head>

    <body>
        <!-- site header with navbar-->
        <header class="bg-light-grey px-2">
            <nav class="navbar navbar-expand-md navbar-light">

                <!-- clickable site logo -->
                <a class="navbar-brand fs-4" href="{% url 'home' %} " aria-label="Link to homepage">
                    <i class="fa-solid fa-cookie-bite"></i>
                    Cook eBook
                </a>

                <!-- Bootstrap expandable navbar button credit: https://getbootstrap.com/docs/5.0/components/navbar/#external-content for controlling the div with id=navbarToggleMobileMenu -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleMobileMenu" aria-controls="navbarToggleMobileMenu" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- the div controlled by the navbar-toggler button -->
                <div class="collapse navbar-collapse" id="navbarToggleMobileMenu">

                    <ul class="navbar-nav text-end ms-auto">
                        {% if user.is_authenticated %}
                        <!-- menu options when a user is logged in -->
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'my_ebook' user.username %}" aria-label="Link to user's my ebook page">My eBook</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_logout' %}" aria-label="Link to logout page">Logout</a>
                        </li>
                        {% else %}
                        <!-- default menu options when users are not logged in -->
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_signup' %}" aria-label="Link to signup page">Signup</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_login' %}" aria-label="Link to login page">Login</a>
                        </li>
                        {% endif %}
                    </ul>

                </div>

            </nav>
        </header>

        <!-- iterating through success messages to display to the user -->
        {% if messages %}
        {% for message in messages %}
        <div class="container">
            <div class="row">
                <div class="col-12 m-2">
                    <div class="alert {{ message.tags }} alert-dismissable fade show" id="msg" role="alert">
                        {{ message | safe }}
                        <!-- dismiss btn using bootstrap alert controls -->
                        <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close message"></button>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        {% endif %}

        <!-- block content provided in the templates which extend base.html -->
        <main>
            {% block content %}
            {% endblock content %}
        </main>

        <!-- site footer -->
        <footer class="bg-light-grey">

            {% if user.is_authenticated %}
            <!-- links for the About page and to Instagram are both visible for logged in -->
            <ul class="nav justify-content-between">
                <li class="nav-item">
                    <a class="nav-link fs-4 p-2 mx-4" href="{% url 'about' %}" aria-label="Link to about page">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link fs-1 px-2 py-1 mx-4" href="https://www.instagram.com/code_by_charlie97/" target = "_blank" rel = "noopener noreffer" aria-label="Link to code_by_charlie97's Instagram account">
                        <i class="fa-brands fa-instagram"></i>
                    </a>
                </li>
            </ul>
            {% else %}
            <!-- only the centralised link to the About page is visible for users which are not logged in -->
            <a class="nav-link fs-4 p-2 mx-4 text-center" href="{% url 'about' %}" aria-label="Link to about page">About</a>
            {% endif %}

            <p class="text-center fs-6 my-0">© 2022 Student of Code Institute</p>

        </footer>
    </body>
</html>

templates/delete_recipe.html
{% extends "base.html" %}
{% load static %}

<!-- additional content for title element -->
{% block head_title_extra %} Delete Recipe {% endblock %}

{% block content %}

<!-- container for all the content to be used with base.html main section -->
<div class="container align-self-center">

    <!-- page heading -->
    <div class="row">
        <div class="col-12 text-center p-2">
            <h1>Are you sure you want to delete {{ recipe.title }}?</h1>
        </div>
    </div>

    <!-- warning message -->
    <div class="row">
        <div class="col-12 text-center p-2">
            <h4>This action cannot be undone</h4>
        </div>
    </div>

    <!-- delete and cancel buttons -->
    <div class="row">
        <div class="col-12 text-center">
            <form method="post">
                {% csrf_token %}

                <!-- cancel button to return the user to their My eBook page without deleting the recipe -->
                <a class="btn btn-secondary" href="{% url 'my_ebook' user.username %}" role="button" aria-label="Cancel and return to my ebook button">Cancel</a>

                <!-- delete button to return the user to their My eBook page after deleting the recipe -->
                <button class="btn btn-danger" type="submit" name="confirm_delete" aria-label="Delete recipe confirmation button">Delete Recipe</button>

            </form>
        </div>
    </div>

</div>

{% endblock %}

templates/my_ebook.html
{% extends "base.html" %}
{% load static %}

<!-- additional content for title element -->
{% block head_title_extra %}My eBook{% endblock %}

{% block content %}

<!-- checking that the logged in user hasn't tried to replace their username with another user's in the url itself -->
{% if user.username == authorised_user %}

<!-- container for all the content to be used with base.html main section if the user is authorised -->
<div class="container">
    <!-- page heading with condition for display the 's' only if the user's username doesn't end with an 's' -->
    <div class="row my-ebook-heading-container p-4">
        <h1>
            {{ user.username }}'
            {% if user.username|slice:"::-1"|slice:":1" != 's' %}
            s
            {% endif %}
            Cook eBook
        </h1>
    </div>

    <!-- searchbar and create button container -->
    <div class="row my-4">

        <!-- searchbar form -->
        <div class="col-12 search-bar-container">
            <form action="{% url 'my_ebook_search_recipes' %}" method="get">
                {% csrf_token %}
                <input type="text" name="search" placeholder="Search Recipe Titles...">
                <button class="btn btn-outline-secondary" type="submit" aria-label="Search button">Search</button>
            </form>
        </div>

        <!-- create recipe button --> 
        <div class="col-12 text-center text-md-end">
            <a class="btn btn-success m-3" href="{% url 'create_recipe' %}" role="button" aria-label="Create new recipe button">Create Recipe</a>
        </div>
        
    </div>

    <!-- search results -->
    {% if recipes %}
    <div class="row search-result-container">

        <!-- number of search results and Return to My eBook button -->
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="m-0">Search results: {{ num_results }}</h2>
             <a class="btn btn-outline-secondary return-link m-3" href="{% url 'my_ebook' user.username %}" role="button" aria-label="Return to My eBook page button">Return to My eBook</a> 
            </div>
        </div>

        <!-- message displayed if no recipes are found in the search -->
        {% if num_results == 0 %}
        <div class="row">
            <div class="col-12 text-center">
                <p>{{ message }}</p>
            </div>
        </div>
        {% else %}

        <!-- displaying the search results with the recipes as recipe cards -->
        <div class="row search-results">
            {% for recipe in recipes %}

            <div class="col-md-4 col-sm-12 my-4">
                <!-- creating the recipe cards -->
                <a class="recipe-card-link" href="{% url 'recipe_details' recipe.slug %}" aria-label="Link to recipe full view">
                    <div class="card h-100">
                        <!-- card cover image -->
                        {% if "placeholder" in recipe.cover_image.url %}
                            <!-- placeholder image in static dir -->
                            <!-- placeholder image credits: https://unsplash.com/photos/5O1ddenSM4g?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink -->
                            <img class="card-img" src="{% static 'images/placeholder-image.jpg' %}" alt="recipe cover image">
                        {% else %}
                            <!-- user specified image in Cloudinary -->
                            <img class="card-img" src=" {{ recipe.cover_image.url }}" alt="recipe cover image">
                        {% endif %}
                        <!-- card body info -->
                        <div class="card-body">
                            <h3 class="card-title"><strong>{{ recipe.title }}</strong></h3>
                            {% if recipe.summary %}
                            <p class="card-text">{{ recipe.summary }}</p>
                            {% else %}
                            <p class="card-text">Open the full view to see more...</p>
                            {% endif %}
                        </div>
                        <!-- showing tags added to the recipe if any -->
                        {% if recipe.tags %}
                        <div class="card-body-tags-container">
                            {% for tag in recipe.tags.all %}
                            <!-- NOTE: using inline styling since the tag color is a database value so this is not an attribute that I will ever change in the external CSS -->
                            <span class="card-body-tags" style="border-color:{{ tag.color }}">{{ tag }}</span>
                            {% endfor %}
                        </div>
                        {% endif %}
                        <!-- card footer info -->
                        <div class="card-footer text-muted">
                            <p class="m-0">
                                Status: {{ recipe.get_public_status_display }}<br>
                                <small>{{ recipe.created_date }}</small> |
                                <small>
                                    Chefs Kisses: {{ recipe.number_of_chefs_kisses }}
                                    <i class="fa-regular fa-face-kiss-wink-heart"></i> 
                                </small>
                            </p>
                        </div>
                    </div>
                </a>
            </div>

            {% endfor %}
        </div>
        {% endif %}

    </div>

    {% else %}

    <!-- container for displaying all the tag tiles (smaller than on homepage) -->
    <div class="row tag-tiles-container justify-content-center">

        <!-- creating the tag tiles -->
        {% for tag in all_tags %}
        <!-- displaying in 6 columns on small and above screen and  -->
            <div class="col-sm-2 col-6 p-1">
                <a class="tag-tile-link" href="{% url 'ebook_search_tags' tag.tag %}" role="button" aria-label="Tag search button">
                    <div class="card">
                        <!-- NOTE: using inline styling since the tag color is a database value so this is not an attribute that I will ever change in the external CSS -->
                        <div class="card-body p-2 my-ebook-tag-tile" style="background-color:{{ tag.color }}">
                            <p class="m-0">{{ tag.tag }}</p>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>

    {% if users_recipes %}
    <!-- user's recipes as recipe cards -->
    <div class="row">

        {% for recipe in users_recipes %}
        <div class="col-md-4 col-sm-12 my-4">
            <!-- creating the recipe cards -->
            <a class="recipe-card-link" href="{% url 'recipe_details' recipe.slug %}" aria-label="Link to recipe full view">
                <div class="card h-100">
                    <!-- card cover image -->
                    {% if "placeholder" in recipe.cover_image.url %}
                        <!-- placeholder image in static dir -->
                        <!-- placeholder image credits: https://unsplash.com/photos/5O1ddenSM4g?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink -->
                        <img class="card-img" src="{% static 'images/placeholder-image.jpg' %}" alt="recipe cover image">
                    {% else %}
                        <!-- user specified image in Cloudinary -->
                        <img class="card-img" src=" {{ recipe.cover_image.url }}" alt="recipe cover image">
                    {% endif %}
                    <!-- card body info -->
                    <div class="card-body">
                        <h3 class="card-title"><strong>{{ recipe.title }}</strong></h3>
                        {% if recipe.summary %}
                        <p class="card-text">{{ recipe.summary }}</p>
                        {% else %}
                        <p class="card-text">Open the full view to see more...</p>
                        {% endif %}
                    </div>
                    <!-- showing tags added to the recipe if any -->
                    {% if recipe.tags %}
                    <div class="card-body-tags-container">
                        {% for tag in recipe.tags.all %}
                        <!-- NOTE: using inline styling since the tag color is a database value so this is not an attribute that I will ever change in the external CSS -->
                        <span class="card-body-tags" style="border-color:{{ tag.color }}">{{ tag }}</span>
                        {% endfor %}
                    </div>
                    {% endif %}
                    <!-- card footer info -->
                    <div class="card-footer text-muted">
                        <p class="m-0">
                            Status: {{ recipe.get_public_status_display }} <br>
                            <small>{{ recipe.created_date }}</small> |
                            <small>
                                Chefs Kisses: {{ recipe.number_of_chefs_kisses }}
                                <i class="fa-regular fa-face-kiss-wink-heart"></i> 
                            </small>
                        </p>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}

    </div>

    {% else %}
    <!-- message to the user if they have no recipes yet -->
    <div class="row">
        <div class="col-12">
            <p class="text-center">
                You don't currently have any recipes in your cook ebook. To make your first recipe, click the Create Recipe button.
            </p>
        </div>
    </div>
    
    {% endif %}
    {% endif %}
</div>

{% else %}

<!-- container for all the content to be used with base.html main section if the user is not authorised -->
<div class="container align-self-center">
    <div class="row">
        <div class="col-12 align-middle">
            <h1 class="text-center fw-bold">This is not your eBook</h1>
        </div>
    </div>
</div>

{% endif %}

{% endblock content %}

templates/recipe_details.html
{% extends "base.html" %}
{% load static %}

<!-- additional content for title element -->
{% block head_title_extra %} - {{ recipe.title }}{% endblock %}

{% block content %}
<!-- container for all the content to be used with base.html main section -->
<div class="container">
    <!-- cover image -->
    <div class="row cover-image-container">
        <div class="col p-0">
            {% if "placeholder" in recipe.cover_image.url %}
                <!-- placeholder image in static dir -->
                <!-- placeholder image credits: https://unsplash.com/photos/5O1ddenSM4g?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink -->
                <img src="{% static 'images/placeholder-image.jpg' %}" alt="recipe cover image">
            {% else %}
                <!-- user specified image in Cloudinary -->
                <img src=" {{ recipe.cover_image.url }}" alt="recipe cover image">
            {% endif %}
        </div>
    </div>

    <!-- recipe title container -->
    <div class="row title-container">
        <div class="col">
            <h1 class="m-0">{{ recipe.title }}</h1>
        </div>
    </div>

    <!-- chef and public status container -->
    <div class="row chef-and-status-container">
        <!-- the content displays in two columns on medium and above screens and as one column by default -->
        <div class="col-md-6 col12">
            <h5>Chef:</h5>
            <p class="m-0">{{ recipe.chef }}</p>
        </div>
        <div class="col-md-6 col-12 text-md-end">
            <h5>Status:</h5>
            <p class="m-0">{{ recipe.get_public_status_display }}</p>
        </div>
    </div>

    <!-- container for displaying any tags the recipe has -->
    {% if recipe.tags %}
    <div class="row">
        <div class="col tags-container">
            {% for tag in recipe.tags.all %}
                <!-- NOTE: using inline styling since the tag color is a database value so this is not an attribute that I will ever change in the external CSS -->
                <span class="recipe-details-tags" style="border-color:{{ tag.color }}">{{ tag }}</span>
            {% endfor %}
        </div> 
    </div>
    {% endif %}

    <hr class="small-centered-hr">

    <!-- ingredient and method container -->
    <div class="row my-4">
        <!-- 2 columns on medium and above screens and 1 column by default -->
        <div class="col-md-6 col-12 recipe-list-container">
            <h4>Ingredients:</h4>
            <ul>
                {% for item in ingredients.all %}
                <li>{{ item }}</li>
                {% endfor %}
            </ul>
        </div>
        <!-- 2 columns on medium and above screens and 1 column by default -->
        <div class="col-md-6 col-12 recipe-list-container">
            <h4>Method:</h4>
            <ol>
                {% for step in method.all %}
                <li>{{ step }}</li>
                {% endfor %}
            </ol>
        </div>
    </div>

    <!-- chefs kisses and edit/delete buttons container -->
    <div class="row">
        <!-- chefs kisses count and button -->
        <div class="col-6 chefs-kisses-container p-2">
            <p>Chefs kisses:</p>
            <p>{{ recipe.number_of_chefs_kisses }}</p>

            {% if user.is_authenticated %}
            <!-- if the user is logged in, the chefs kiss icon is a clickable icon to toggle between giving the recipe a chefs kiss and taking away the user's chefs kiss -->
            <form class="d-inline" method="post" action="{% url 'recipe_chefs_kiss' recipe.slug %}">
                {% csrf_token %}
                <!-- if chefs_kiss = True then the icon has fa-solid style -->
                {% if chefs_kiss %}
                <button type="submit" name="recipe_id" value="{{ recipe.slug }}" class="btn" aria-label="Un-Chef's kiss button">
                    <i class="fa-solid fa-face-kiss-wink-heart chef-kiss-icon"></i>
                </button>
                {% else %}
                <!-- if chefs_kiss = False then the icon has fa-regular style -->
                <button type="submit" name="recipe_id" value="{{ recipe.slug }}" class="btn text-muted" aria-label="Chef's kiss button">
                    <i class="fa-regular fa-face-kiss-wink-heart chef-kiss-icon"></i>
                </button>
                {% endif %}
            </form>
            <!-- if user is not logged in the icon is not a button -->
            {% else %}
            <i class="fa-regular fa-face-kiss-wink-heart chef-kiss-icon"></i>
            {% endif %} 
        </div>

        <!-- ensuring the user is logged in and the chef for this recipe in order to display the edit and delete buttons -->
        {% if user.is_authenticated and user.id == recipe.chef.id %}
        <div class="col-6 text-end p-2">
            <!-- edit button -->
            <a class="btn btn-primary" href="{% url 'edit_recipe' recipe.slug %}" role="button" aria-label="Edit recipe button">Edit</a>
            <!-- delete button -->
            <a class="btn btn-danger" href="{% url 'delete_recipe' recipe.slug %}" role="button" aria-label="Delete recipe button">Delete</a>
        </div>
        {% endif %}
    </div>

{% endblock content %}